apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-prediction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-prediction-app
  template:
    metadata:
      labels:
        app: weather-prediction-app
    spec:
      containers:
      - name: weather-prediction-app
        image: weather-prediction-app:local
        imagePullPolicy: Never  # Important for local image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weather-prediction-service
spec:
  type: NodePort
  selector:
    app: weather-prediction-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007