stages:
  collect_data:
    cmd: python collect_data.py
    outs:
      - data/raw/raw_data.csv

  preprocess_data:
    cmd: python preprocess_data.py
    deps:
      - data/raw/raw_data.csv
    outs:
      - data/processed/processed_data.csv

  train_model:
    cmd: python train_model.py
    deps:
      - data/processed/processed_data.csv
    outs:
      - model/temperature_model.pkl
    metrics:
      - metrics.json