name: CI Pipeline

on:
  push:
    branches:
      - feature-cicd

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web_app/backend/requirements.txt
        pip install pytest

    - name: Run backend unit tests
      run: |
        cd web_app/backend
        python -m pytest

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-prediction-app:latest
