name: CI Pipeline

on:
  push:
    branches:
      - test

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 5: Install DVC and configure
    - name: Install DVC
      run: |
        pip install dvc dvc-gdrive
        dvc version

    # Step 6: Create credentials.json
    - name: Create credentials.json
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        echo "$GDRIVE_CREDENTIALS_DATA" > credentials.json

    # Step 7: Configure DVC Remote
    - name: Modify DVC Remote
      run: |
        dvc remote modify --local myremote gdrive_service_account_json_file_path credentials.json

    # Step 8: Pull DVC Tracked Files
    - name: Pull DVC tracked files
      run: |
        dvc pull -v

    # Step 9: Install backend dependencies
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web_app/backend/requirements.txt
        pip install pytest

    # Step 10: Run backend unit tests
    - name: Run backend unit tests
      run: |
        cd web_app/backend
        python -m pytest

    # Step 11: Build and Push Docker Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-prediction-app:latest
