name: CD Pipeline

on:
  pull_request:
    branches:
      - prod
    types:
      - closed

jobs:
  deploy-to-minikube:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Minikube
      uses: medyagh/setup-minikube@master

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weather-prediction-app:latest

    - name: Load Docker image to Minikube
      run: |
        minikube image load ${{ secrets.DOCKERHUB_USERNAME }}/weather-prediction-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml

    - name: Check deployment status
      run: |
        kubectl get deployments
        kubectl get services
        kubectl get pods
        
    - name: Troubleshoot Deployment
      run: |
        kubectl describe deployment weather-prediction-app
        kubectl describe pods
        kubectl get events

    - name: Get Minikube IP and Service URL
      run: |
          minikube service list
          minikube service weather-prediction-service --url
